import { redactText } from "../security/redactor.ts";
import type { GenerationPlan, ReplayStepPlan } from "./types.ts";

/**
 * Free text embedded into the generated `.spec.ts` source is redacted
 * again here — `report.json`/`flow.json` have already been through
 * redaction once, but a generated test file is a new persistence
 * boundary (the same defense-in-depth pattern already used for
 * `report.md`, see src/report/markdown.ts).
 */
function literal(text: string): string {
  return JSON.stringify(redactText(text));
}

function renderReplayStepLine(step: ReplayStepPlan): string {
  switch (step.kind) {
    case "navigate":
      return `  await page.goto(${literal(step.url)});`;
    case "fill":
      return `  await ${step.locator.code}.fill(${literal(step.value)});`;
    case "click":
      return `  await ${step.locator.code}.click();`;
  }
}

/**
 * A bare promise-returning expression for the same step — no `await`, no
 * trailing `;` — for use as one element of a `Promise.all([...])` array
 * literal (network rules race the trigger action against a response/
 * failure listener), where a full statement would be a syntax error.
 */
function renderReplayStepExpr(step: ReplayStepPlan): string {
  switch (step.kind) {
    case "navigate":
      return `page.goto(${literal(step.url)})`;
    case "fill":
      return `${step.locator.code}.fill(${literal(step.value)})`;
    case "click":
      return `${step.locator.code}.click()`;
  }
}

function header(plan: GenerationPlan): string {
  return [
    "// Generated by WebCheck",
    `// Finding: ${plan.findingId}`,
    `// Rule: ${plan.ruleId}`,
    `// Source run: ${plan.runId}`
  ].join("\n");
}

function renderRtException(plan: Extract<GenerationPlan, { ruleId: "RT-EXCEPTION" }>): string {
  const prefixLines = plan.prefixSteps.map(renderReplayStepLine);
  const triggerLine = renderReplayStepLine(plan.triggerStep);

  return `${header(plan)}
import { test, expect } from "@playwright/test";

const BASE_URL = process.env.WEBCHECK_BASE_URL ?? ${literal(plan.baseUrl)};

test(${literal(`WebCheck regression: ${plan.findingId} (RT-EXCEPTION)`)}, async ({ page }) => {
  const pageErrors: Error[] = [];
  page.on("pageerror", (error) => {
    pageErrors.push(error);
  });

  await page.goto(BASE_URL);
${prefixLines.join("\n")}${prefixLines.length > 0 ? "\n" : ""}${triggerLine}

  expect(
    pageErrors,
    \`expected no uncaught runtime exception; originally observed: ${literal(plan.observedMessage)}\`
  ).toHaveLength(0);
});
`;
}

function renderNetworkError(plan: Extract<GenerationPlan, { ruleId: "NW-HTTP-ERROR" }>): string {
  const prefixLines = plan.prefixSteps.map(renderReplayStepLine);
  const triggerExpr = renderReplayStepExpr(plan.triggerStep);

  return `${header(plan)}
import { test, expect } from "@playwright/test";

const BASE_URL = process.env.WEBCHECK_BASE_URL ?? ${literal(plan.baseUrl)};
const REQUEST_METHOD = ${literal(plan.method)};
const REQUEST_PATH = ${literal(plan.urlPath)};

test(${literal(`WebCheck regression: ${plan.findingId} (NW-HTTP-ERROR)`)}, async ({ page }) => {
  await page.goto(BASE_URL);
${prefixLines.join("\n")}${prefixLines.length > 0 ? "\n" : ""}
  const [response] = await Promise.all([
    page.waitForResponse(
      (candidate) => new URL(candidate.url()).pathname === REQUEST_PATH && candidate.request().method() === REQUEST_METHOD
    ),
    ${triggerExpr}
  ]);

  expect(
    response.status(),
    \`expected HTTP status < 400 for \${REQUEST_METHOD} \${REQUEST_PATH}, but got \${response.status()}\`
  ).toBeLessThan(400);
});
`;
}

function renderTransportFailure(plan: Extract<GenerationPlan, { ruleId: "NW-TRANSPORT-FAILURE" }>): string {
  const prefixLines = plan.prefixSteps.map(renderReplayStepLine);
  const triggerExpr = renderReplayStepExpr(plan.triggerStep);

  return `${header(plan)}
import { test, expect } from "@playwright/test";

const BASE_URL = process.env.WEBCHECK_BASE_URL ?? ${literal(plan.baseUrl)};
const REQUEST_METHOD = ${literal(plan.method)};
const REQUEST_PATH = ${literal(plan.urlPath)};

test(${literal(`WebCheck regression: ${plan.findingId} (NW-TRANSPORT-FAILURE)`)}, async ({ page }) => {
  await page.goto(BASE_URL);
${prefixLines.join("\n")}${prefixLines.length > 0 ? "\n" : ""}
  // Raced, not sequential: a fixed backend produces a normal response
  // (no requestfailed event ever fires), so only one of these two ever
  // resolves for a given request — whichever it is tells us whether the
  // transport failure still reproduces.
  const [outcome] = await Promise.all([
    Promise.race([
      page
        .waitForEvent(
          "requestfailed",
          (request) => new URL(request.url()).pathname === REQUEST_PATH && request.method() === REQUEST_METHOD
        )
        .then((request) => ({ kind: "failed" as const, request })),
      page
        .waitForResponse(
          (candidate) => new URL(candidate.url()).pathname === REQUEST_PATH && candidate.request().method() === REQUEST_METHOD
        )
        .then((response) => ({ kind: "response" as const, response }))
    ]),
    ${triggerExpr}
  ]);

  expect(
    outcome.kind,
    outcome.kind === "failed"
      ? \`expected \${REQUEST_METHOD} \${REQUEST_PATH} to succeed at the transport level, but it failed: \${outcome.request.failure()?.errorText ?? "unknown"}\`
      : ""
  ).toBe("response");
});
`;
}

/**
 * Pure, deterministic rendering of a `GenerationPlan` into Playwright
 * Test source: no filesystem access, no execution, no mutation. The same
 * plan always produces byte-identical output.
 */
export function renderGeneratedTest(plan: GenerationPlan): string {
  switch (plan.ruleId) {
    case "RT-EXCEPTION":
      return renderRtException(plan);
    case "NW-HTTP-ERROR":
      return renderNetworkError(plan);
    case "NW-TRANSPORT-FAILURE":
      return renderTransportFailure(plan);
  }
}
