// Generated by WebCheck
// Finding: finding-0001
// Rule: RT-EXCEPTION
// Source run: run-rt-1
import { test, expect } from "@playwright/test";

const BASE_URL = process.env.WEBCHECK_BASE_URL ?? "http://127.0.0.1:4300";

test("WebCheck regression: finding-0001 (RT-EXCEPTION)", async ({ page }) => {
  const pageErrors: Error[] = [];
  page.on("pageerror", (error) => {
    pageErrors.push(error);
  });

  await page.goto(BASE_URL);
  await page.getByTestId("throw-error-button").click();

  expect(
    pageErrors,
    `expected no uncaught runtime exception; originally observed: "Fixture: simulated uncaught exception"`
  ).toHaveLength(0);
});
