import { describe, expect, it } from "vitest";
import { planGeneratedTest } from "../../src/testgen/generator.ts";
import { renderGeneratedTest } from "../../src/testgen/render.ts";
import type { GenerationPlan } from "../../src/testgen/types.ts";
import { networkErrorScenario, rtExceptionScenario, transportFailureScenario } from "../helpers/testgen-scenarios.ts";

function planFor(scenario: ReturnType<typeof rtExceptionScenario>, findingId = "finding-0001"): GenerationPlan {
  const outcome = planGeneratedTest({ ...scenario, findingId });
  if (outcome.status !== "planned") throw new Error(`expected planned, got ${outcome.status}: ${outcome.reason}`);
  return outcome.plan;
}

describe("renderGeneratedTest", () => {
  it("9. renders a valid RT-EXCEPTION test with a pageerror-presence assertion", () => {
    const source = renderGeneratedTest(planFor(rtExceptionScenario()));
    expect(source).toContain('import { test, expect } from "@playwright/test";');
    expect(source).toContain("page.on(\"pageerror\"");
    expect(source).toContain("page.getByTestId(\"throw-error-button\").click();");
    expect(source).toContain("expect(\n    pageErrors,");
    expect(source).toContain(").toHaveLength(0);");
  });

  it("10. renders a valid NW-HTTP-ERROR test asserting status < 400", () => {
    const source = renderGeneratedTest(planFor(networkErrorScenario()));
    expect(source).toContain('const REQUEST_METHOD = "POST";');
    expect(source).toContain('const REQUEST_PATH = "/api/login";');
    expect(source).toContain("page.waitForResponse(");
    expect(source).toContain(").toBeLessThan(400);");
    // trigger step used as a bare expression inside Promise.all, not a statement
    expect(source).toContain('page.getByRole("button", { name: "Login" }).click()\n');
    expect(source).not.toContain("await page.getByRole(\"button\", { name: \"Login\" }).click();\n  ]);");
  });

  it("11. renders a valid NW-TRANSPORT-FAILURE test racing requestfailed against a response", () => {
    const source = renderGeneratedTest(planFor(transportFailureScenario()));
    expect(source).toContain('const REQUEST_METHOD = "GET";');
    expect(source).toContain('const REQUEST_PATH = "/api/transport-fail";');
    expect(source).toContain(".waitForEvent(");
    expect(source).toContain('"requestfailed",');
    expect(source).toContain("Promise.race([");
    expect(source).toContain('.toBe("response");');
  });

  it("12. never emits waitForTimeout", () => {
    for (const scenario of [rtExceptionScenario(), networkErrorScenario(), transportFailureScenario()]) {
      const source = renderGeneratedTest(planFor(scenario));
      expect(source).not.toContain("waitForTimeout");
    }
  });

  it("13. never embeds an absolute machine path", () => {
    for (const scenario of [rtExceptionScenario(), networkErrorScenario(), transportFailureScenario()]) {
      const source = renderGeneratedTest(planFor(scenario));
      expect(source).not.toMatch(/[A-Za-z]:\\/);
      expect(source).not.toMatch(/\/(Users|home)\//);
    }
  });

  it("14. header comment carries correct Finding/Rule/Source run metadata", () => {
    const scenario = rtExceptionScenario();
    const source = renderGeneratedTest(planFor(scenario));
    expect(source).toContain("// Generated by WebCheck");
    expect(source).toContain("// Finding: finding-0001");
    expect(source).toContain("// Rule: RT-EXCEPTION");
    expect(source).toContain(`// Source run: ${scenario.runId}`);
  });

  it("4. produces byte-identical output for the same plan", () => {
    const plan = planFor(rtExceptionScenario());
    expect(renderGeneratedTest(plan)).toBe(renderGeneratedTest(plan));
  });

  it("8. redacts a key=value-shaped secret embedded in a fill value even if upstream redaction was bypassed", () => {
    const scenario = networkErrorScenario();
    const flow = {
      ...scenario.flow,
      steps: scenario.flow.steps.map((step) =>
        step.type === "fill" && step.target.label === "Email"
          ? { ...step, value: "token=SENTINEL_ABC123 leaked in a fill value" }
          : step
      )
    };
    const source = renderGeneratedTest(planFor({ ...scenario, flow }));
    expect(source).not.toContain("SENTINEL_ABC123");
    expect(source).toContain("[REDACTED]");
  });

  it("does not mutate the input plan", () => {
    const plan = planFor(rtExceptionScenario());
    const clone = JSON.parse(JSON.stringify(plan));
    renderGeneratedTest(plan);
    expect(plan).toEqual(clone);
  });
});
